### ISSUE TITLE
Fatal error encountered.

### ISSUE THREAD

**Issue by Nevolox** [DevilXD/TwitchDropsMiner#14]
After i succesfuly log in, i'm getting disconnected with that error

2022-04-11 12:40:43.901:	  ERROR:	Fatal error encountered:
Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 207, in run
  File "twitch.py", line 916, in fetch_inventory
  File "gui.py", line 950, in add_campaign
  File "cache.py", line 92, in get
  File "PIL\Image.py", line 2297, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Username\\Documents\\Twitch Drops Miner\\cache\\d9b68fc4f33e77343dfc00020.png'

**Comment by DevilXD** [comment]
Hello o/

Strange, given that this `cache` folder is created by the application itself, and it had no problem saving the images inside. This error means that it can't read them back. Are you able to open any image inside this `cache` folder yourself?

**Comment by Nevolox** [comment]
> Also, can you make sure that there's no interference from like, antivirus software?

Alright yeah it was the anti virus software. I don't know why i have not tried it haha 👍

**Comment by DevilXD** [comment]
Oh. Well, glad you got it working =) The more functionality like this is added, the more chances there is for "misfires" and issues like this, unfortunately. Guess this can be closed now. Enjoy :slightly_smiling_face:
