### ISSUE TITLE
GQL error

### ISSUE THREAD

**Issue by allanf181** [DevilXD/TwitchDropsMiner#153]
17:39:29: Fatal error encountered:
17:39:29: 
17:39:29: Traceback (most recent call last):
17:39:29:   File "main.py", line 175, in <module>
17:39:29:   File "asyncio\base_events.py", line 616, in run_until_complete
17:39:29:   File "twitch.py", line 759, in run
17:39:29:   File "twitch.py", line 908, in _run
17:39:29:   File "twitch.py", line 1677, in get_live_streams
17:39:29:   File "twitch.py", line 1534, in gql_request
17:39:29: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['game', 'streams']}]
17:39:29: 
17:39:29: Exiting...
17:39:30: 
17:39:30: Application Terminated.
17:39:30: Close the window to exit the application.

**Comment by DevilXD** [comment]
Hello o/

This is already fixed in the latest master per https://github.com/DevilXD/TwitchDropsMiner/commit/e511932339eb2333ddb92e3ec90c524eb3067fed

**Comment by 1003999458** [comment]
When will you release the new version?

**Comment by 1003999458** [comment]
> 你好哦/
> 
> 这已经在每个[e511932的最新主控中修复](https://github.com/DevilXD/TwitchDropsMiner/commit/e511932339eb2333ddb92e3ec90c524eb3067fed)

When will you release the new version?

**Comment by DevilXD** [comment]
@1003999458 When it's ready. There's no particular timeframe to it for now.

**Comment by Totesfleisch** [comment]
Isnt the latest Version the one you can get trough cloning the git? I have done that and i get the GQL Error regardless.

**Comment by Bungeetaco** [comment]
> Isnt the latest Version the one you can get trough cloning the git? I have done that and i get the GQL Error regardless.

Same thing here. Built the Windows package after cloning the git repo and the application seems to stop working after a while.

**Comment by DevilXD** [comment]
The original error traceback mentions the exception originating from L1534. There is only a simple assignment on that line in the latest master: https://github.com/DevilXD/TwitchDropsMiner/blob/master/twitch.py#L1534

If you are getting this error, please double check you are actually using the latest master. If so, I'd like to see the updated traceback here.

**Comment by Bungeetaco** [comment]
I've ran a new build with build.bat from a fresh cloned repo just now. If the error occurs again, I'll post a traceback log here.

**Comment by Totesfleisch** [comment]
I didnt actually redownloaded the files, but the Bot has been running fine all Day long after crashing like 7 Times in a Row in the Morning. Seems like it was an temporary Issue thats gone now, or atleast only one that occurs extremely rarely and i was unlucky.

**Comment by mcykin** [comment]
hi,i'm using the lateset v15,my computer and my cloud server both running this bug,
did this version fix this bug,or i'll need to wait for v16?
thx
