### ISSUE TITLE
[Feature Request] Headless mode

### ISSUE THREAD

**Issue by Toucan-Sam** [DevilXD/TwitchDropsMiner#17]
Would be great if there was a `--headless` flag to allow it to not spawn the UI at all.

Separately, with a `--headless` option, being able to set the location of the `cookie.jar` and the `settings.json` files would be excellent.

Would make the application much easier to dockerize. ;)

**Comment by DevilXD** [comment]
Hello o/

Yes, this is something I do plan on adding to the application at some point. My available time reserves have shrunk quite a bit recently, so I'm putting aside this project for now, but this issue should remain open, to be closed once such mode will be added at some point in the future.

**Comment by herhor67** [comment]
I'd love a headless mode to be implemented, I'm using another bot but it's not being maintained and with recent changes on twitch, welp...
This one seems like a great alternative, but I only have a headless ubuntu server, so, yeah.

**Comment by DevilXD** [comment]
Right now, it'd be cool to have the application back in working state first. But yes, if you'd be interested in Linux support, please refer to discussion in #35. IIRC, I asked for any traceback that'd arise from running the app on Linux, excluding the current on-going issue from #40 of course.

**Comment by DevilXD** [comment]
As a quick update on the state of the headless mode support.

Right now, the application remains to be strictly tied with it's GUI and procedures responsible for updating it. The backup Chrome login available in the latest master is something that won't work on a headless machine, as it opens a browser window for the user to interact with. Other than that, the headless mode has been put on the backburner of things to consider possibly adding in the future, once the core application stops being broken by Twitch introducing their changes.

**Comment by Pr0mises** [comment]
> The backup Chrome login available in the latest master is something that won't work on a headless machine, as it opens a browser window for the user to interact with.

You just need the ID that is printed to the UI console and activate it via the host you're operating the headless machine from. Or use your phone to link the ID. So that option is even better than the normal login or via auth_token for headless/docker.
Just don't open a chrome tab [```webbrowser.open_new_tab("https://www.twitch.tv/activate")```](https://github.com/DevilXD/TwitchDropsMiner/blob/3892dfe59e8835486966cd668c9e128c36b7cd95/gui.py#L500) when in headless mode and everything is fine.

**Comment by DevilXD** [comment]
@Pr0mises That's still not the main problem, the main problem still remains:

> the application remains to be strictly tied with it's GUI and procedures responsible for updating it.

Because of this, it's impossible to go anywhere with headless mode, before redoing the whole GUI layer of the application, and that's something that exists on the very end of my TODO list - there are more important things to take care of first, like the tree-event-based rewrite of the memory structure, #107 or #110.

**Comment by Pr0mises** [comment]
That's correct, that's why I only stated that the login is possible with headless. So all good, thanks for your work :)

**Comment by Windows200000** [comment]
For anyone interested I got it working by using Xvfb and copying configs and cookies from a TDM install on windows.

**Comment by scmanjarrez** [comment]
Just in case someone is getting this error:
```
Traceback (most recent call last):
  File "/home/pi/twitch_drops/TwitchDropsMiner/venv/lib/python3.9/site-packages/pystray/_appindicator.py", line 24, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/home/pi/twitch_drops/TwitchDropsMiner/venv/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/twitch_drops/TwitchDropsMiner/main.py", line 29, in <module>
    from twitch import Twitch
  File "/home/pi/twitch_drops/TwitchDropsMiner/twitch.py", line 39, in <module>
    from gui import GUIManager
  File "/home/pi/twitch_drops/TwitchDropsMiner/gui.py", line 21, in <module>
    import pystray
  File "/home/pi/twitch_drops/TwitchDropsMiner/venv/lib/python3.9/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/home/pi/twitch_drops/TwitchDropsMiner/venv/lib/python3.9/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/home/pi/twitch_drops/TwitchDropsMiner/venv/lib/python3.9/site-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
  File "/home/pi/twitch_drops/TwitchDropsMiner/venv/lib/python3.9/site-packages/pystray/_appindicator.py", line 27, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/home/pi/twitch_drops/TwitchDropsMiner/venv/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available
```
You may need to use gtk in PYSTRAY_BACKEND:
```
PYSTRAY_BACKEND=gtk python main.py
```
And install this libraries
```
sudo apt install python3-gi gobject-introspection gir1.2-gtk-3.0
```

**Comment by Laurazepam** [comment]
Didn't like the idea of running a whole ass docker container for this, so I created a systemd service instead.
I decided to build the executable, but it should work the same when running from source. TDM and Xvfb pretty much _need to_ be separate services, there might be a workaround, but that's just not how systemd is supposed to be used (only TDM needs to be enabled). The idea with the restart policy was to "recover" from issues on Twitch's end that result in fatal errors, not entirely sure if that actually works tho as it hasn't happened yet. I might put this on the AUR at some point, but for now here it is in case anyone wants to use it.

```
TwitchDropsMiner.service

[Unit]
Description=TwitchDropsMiner
After=network-online.target
Requires=xvfb.service

[Service]
User=twitch
Group=twitch
Environment="DISPLAY=:99"
ExecStart=/bin/sh -c "/opt/TwitchDropsMiner/dist/TwitchDropsMiner"
KillMode=mixed
Restart=on-failure
RestartSec=60
RestartMaxDelaySec=1800
RestartSteps=30

[Install]
WantedBy=multi-user.target
```

```
xvfb.service

[Unit]
Description=X virtual framebuffer (for TwitchDropsMiner)

[Service]
ExecStart=/usr/bin/Xvfb :99 -screen 0 1x2x8
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by wzcsimon123** [comment]
I built a Docker image for this using xrdp and Openbox. Resource usage: 370MiB RAM / 1.4GiB disk.
```yaml
services:
  twitch-miner:
    image: wzcsimon/twitch-drops-miner-xrdp:latest
    container_name: twitch-drops-miner
    privileged: true
    ports:
      - "3390:3389"  
    environment:
      - RDP_PASS=passwd 
    volumes:
      - ./data:/app
    restart: unless-stopped

1. Download Twitch.Drops.Miner.Linux.PyInstaller-x86_64.zip.
2. Unzip and rename the executable from Twitch Drops Miner (by DevilXD) to Twitch.
3. Place the renamed Twitch file and your cookies.jar into the ./data directory.

Once the container is running, connect via any RDP client to  start the application.

**Comment by adrianipopescu** [comment]
do note, you can start from the kasmvnc base image from lsio, that also gives you http web ui as well as the vnc port
