### ISSUE TITLE
Why does he make such a mistake?

### ISSUE THREAD

**Issue by 1105949368** [DevilXD/TwitchDropsMiner#19]
```py
Please log in to continue.
2022-06-08 17:58:39.670:	  ERROR:	Fatal error encountered:
Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1175, in _create_direct_connection
  File "aiohttp\connector.py", line 986, in _wrap_create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "async_timeout\__init__.py", line 125, in __aexit__
  File "async_timeout\__init__.py", line 208, in _do_exit
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "twitch.py", line 792, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 539, in _request
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://passport.twitch.tv/login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 165, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 172, in run
  File "twitch.py", line 746, in check_login
  File "twitch.py", line 669, in _login
  File "contextlib.py", line 171, in __aenter__
  File "twitch.py", line 800, in request
exceptions.RequestException: Ran out of attempts while handling a request: (method='POST', url='https://passport.twitch.tv/login', attempts=5, kwargs={'json': {'client_id': 'kimne78kx3ncx6brgo4mv6wki5h1ko', 'undelete_user': False, 'remember_me': True, 'username': 'selfishPup4273', 'password': '...'}})
Fatal error encountered:

Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1175, in _create_direct_connection
  File "aiohttp\connector.py", line 986, in _wrap_create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "async_timeout\__init__.py", line 125, in __aexit__
  File "async_timeout\__init__.py", line 208, in _do_exit
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "twitch.py", line 792, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 539, in _request
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://passport.twitch.tv/login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 165, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 172, in run
  File "twitch.py", line 746, in check_login
  File "twitch.py", line 669, in _login
  File "contextlib.py", line 171, in __aenter__
  File "twitch.py", line 800, in request
exceptions.RequestException: Ran out of attempts while handling a request: (method='POST', url='https://passport.twitch.tv/login', attempts=5, kwargs={'json': {'client_id': 'kimne78kx3ncx6brgo4mv6wki5h1ko', 'undelete_user': False, 'remember_me': True, 'username': 'selfishPup4273', 'password': '...'}})

Exiting...

Application Terminated.
Close the window to exit the application.
```

**Comment by 1105949368** [comment]
I didn't find where to download V12, my current one is V11

**Comment by DevilXD** [comment]
Hello o/

First of all, you've left in your Twitch's account password in the traceback. I've edited it out, but I'd recommend changing your password ASAP to avoid having your account compromised. I should probably add a way for it to censor it automatically when the traceback is printed, since having the traceback is useful, but having the user's password is useless and hurts only them. I'll try to make it a thing for V12 if possible.

Second of all, this looks like a general Twitch connection issue. Are you able to access the Twitch website normally? If so, please let me know your general area of residence (country or a part of continent is fine) and if you're using any proxies or not.

Third of all, V12 is not available for public download just yet, at least in an executable release form. Absolute latest version can always be obtained from source master branch.

**Comment by 1105949368** [comment]
Can I use TOKEN to log into my account directly.

**Comment by DevilXD** [comment]
Sort of. It'd be possible to manually edit the cookies file to paste in a new token easily, however it'd need to already contain the proper structure that'd show you where to paste it in, and that's not possible unless you've already managed to log in successfully before. Another way would be to run the application from source and just set a breakpoint somewhere after the login request is sent but before it's processed, and then use the variable lookup to change the `auth_key` attribute from `None` to a string containing the token. Both of these are pretty complicated to do for an average user, so I'd assume you're not interested.

Instead, I'd rather try to solve your login issue. Again, I'll need your approximate world location / region and an information if you're using a proxy or not. Normally, an error like this could occur when you'd be using a proxy, but then forget to specify this in the application settings here:
![obraz](https://user-images.githubusercontent.com/4180725/172715098-c15aa7b7-84bd-4b19-a944-32fee09ecc05.png)

Please answer my questions, otherwise I won't be able to help you.

**Comment by 1105949368** [comment]
No active campaigns to mine drops for. Waiting for an active campaign...
No active campaigns to mine drops for. Waiting for an active campaign...
![image](https://user-images.githubusercontent.com/64571015/172757706-05adb7dc-df18-4da2-b433-944efda2cd30.png)

The agent I used in Hong Kong has solved the login problem now, but why I added the game and clicked Reload, but he still can't drop it.

**Comment by DevilXD** [comment]
There has to be an active campaign for Lost Ark to begin mining - this message will display if that's not the case. If you've added the game and clicked on Reload already, you should be good to go. https://www.twitch.tv/datmodz is currently streaming Lost Ark with drops enabled, so they should be progressing. Is that not the case?

**Comment by 1105949368** [comment]
![image](https://user-images.githubusercontent.com/64571015/172808574-21c5e1ac-220d-4651-a0b6-2556e1bd2c23.png)
![image](https://user-images.githubusercontent.com/64571015/172808582-f6286447-79b0-4326-917c-5843dffe9355.png)
It's always been like this. my friends

**Comment by DevilXD** [comment]
Your inventory appears to be empty, meaning that you don't have the account linked. The application explicitly mentions that it doesn't manage account links - you are the one responsible for doing that yourself.

Go to https://www.twitch.tv/drops/campaigns and choose the `Lost Ark` campaign, then connect up your account: 
![obraz](https://user-images.githubusercontent.com/4180725/172903037-2675f5ae-fb70-4e5f-8481-02d2f704df33.png)

Once this is done and it'll be saying "Connected", restart the application and it should start mining properly.

**Comment by 1105949368** [comment]
Can I first receive the game reward and then link the account, because it is not displayed now.

**Comment by DevilXD** [comment]
The thing is, the miner won't pick up the campaign for mining if the account isn't linked. So while this is possible to do on Twitch in general, pretty sure, you'd have to just watch the streams the usual way, without using the application.
