### ISSUE TITLE
Crash/Termination after drop claim

### ISSUE THREAD

**Issue by Suz1e** [DevilXD/TwitchDropsMiner#20]
Please log in to continue.
2022-06-17 07:13:49.740:	  ERROR:	Fatal error encountered:
Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 179, in run
  File "twitch.py", line 788, in check_login
  File "twitch.py", line 708, in _login
  File "contextlib.py", line 171, in __aenter__
  File "twitch.py", line 833, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 559, in _request
  File "aiohttp\client_reqrep.py", line 913, in start
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 179, in run
  File "twitch.py", line 788, in check_login
  File "twitch.py", line 708, in _login
  File "contextlib.py", line 171, in __aenter__
  File "twitch.py", line 833, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 559, in _request
  File "aiohttp\client_reqrep.py", line 913, in start
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError

Exiting...

Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment]
Hello o/

The traceback suggests an application start, rather than something that happened during mining and after claiming a drop. This gives me no useful information I could work with, a general timeout error like this could happen due to something as simple as connection problems. Does this happen reliably in any particular case?

**Comment by Suz1e** [comment]
I have solved this problem, it is the problem of not being able to connect to Twitch

**Comment by DevilXD** [comment]
Yeah, that'd generally yield an error like this. Since it seems to be resolved now, this issue can be closed.
