### ISSUE TITLE
Can't open with raspberry pi 64 bit

### ISSUE THREAD

**Issue by yukaiin** [DevilXD/TwitchDropsMiner#244]
When I open the linux executable nothing happens. When I try opening it in terminal I get this error

```
"/home/alex/Desktop/Twitch Drops Miner (by DevilXD)"
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 a450806d built on Jul  4 2023 07:29:14
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 43 Env var
Looking for /home/alex/Desktop/Twitch Drops Miner (by DevilXD)
Rename process to "Twitch Drops Miner (by DevilXD)"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 a450806d built on Jul  4 2023 07:29:14
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 46 Env var
Looking for /home/alex/Desktop/Twitch Drops Miner (by DevilXD)
Rename process to "Twitch Drops Miner (by DevilXD)"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Using emulated /tmp/_MEIJn2gKP/libpython3.10.so.1.0
Using native(wrapped) libm.so.6
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_struct.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/zlib.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/libffi.so.7
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_opcode.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_bz2.cpython-310-x86_64-linux-gnu.so
Using native(wrapped) libbz2.so.1
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_lzma.cpython-310-x86_64-linux-gnu.so
Using native(wrapped) liblzma.so.5
Using emulated /tmp/_MEIJn2gKP/lib-dynload/math.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_bisect.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_random.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_sha512.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/fcntl.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_posixsubprocess.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/select.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/binascii.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/grp.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_datetime.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/pyexpat.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_socket.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/array.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_heapq.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_queue.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_csv.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_json.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_pickle.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_multiprocessing.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_posixshmem.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_ssl.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/libssl.so.1.1
Using emulated /tmp/_MEIJn2gKP/libcrypto.so.1.1
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_contextvars.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_asyncio.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/_MEIJn2gKP/libtk8.6.so
Using emulated /tmp/_MEIJn2gKP/libtcl8.6.so
Using native(wrapped) libXft.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libXss.so.1
Using native(wrapped) libXext.so.6
Error: Symbol _XInitImageFuncPtrs not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e7178 (0x312f0) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: Symbol XftDrawDestroy not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e72b0 (0x31560) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: Symbol XftDrawGlyphFontSpec not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e7320 (0x31640) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: Symbol XftListFonts not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e7370 (0x316e0) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: Symbol XftCharIndex not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e73b8 (0x31770) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: Symbol XftGlyphExtents not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e7440 (0x31880) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: Symbol XftDefaultSubstitute not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e7560 (0x31ac0) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: Symbol XftXlfdParse not found, cannot apply R_X86_64_JUMP_SLOT @0x1023e75d0 (0x31ba0) in /tmp/_MEIJn2gKP/libtk8.6.so
Error: relocating Plt symbols in elf libtk8.6.so
Error initializing needed lib libtk8.6.so
Error loading one of needed lib
Error initializing needed lib /tmp/_MEIJn2gKP/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "tkinter/__init__.py", line 37, in <module>
ImportError: Cannot dlopen("/tmp/_MEIJn2gKP/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so"/0x102107b60, 2)

[2287497] Failed to execute script 'main' due to unhandled exception!

```

**Comment by guihkx** [comment]
The executable is built for x86-64 CPUs, not ARM.

In any case, there's always the option to build/run the app directly from source. Check out [the wiki](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running#manual-instructions).

**Comment by Walter-o** [comment]
I can confirm it works on ARMv7 and ARMv8/ARM64.

Just run python and it should work.

**Comment by DevilXD** [comment]
Yeah, the "linux" build is for a non-ARM architecture. There's currently no official builds for ARM, but you're welcome to run it from source, or create an ARM build yourself, by following the instructions: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running#manual-instructions
