### ISSUE TITLE
I don't have 2FA turned on, but I can't log in

### ISSUE THREAD

**Issue by LegendAdmin** [DevilXD/TwitchDropsMiner#25]
This is the log information: 
```
Please log in to continue.
2022-06-28 14:00:05.212:	  ERROR:	Fatal error encountered:
Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 179, in run
  File "twitch.py", line 788, in check_login
  File "twitch.py", line 711, in _login
  File "aiohttp\client_reqrep.py", line 1103, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://passport.twitch.tv/login')
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 179, in run
  File "twitch.py", line 788, in check_login
  File "twitch.py", line 711, in _login
  File "aiohttp\client_reqrep.py", line 1103, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://passport.twitch.tv/login')

Exiting...

Application Terminated.
Close the window to exit the application.
```

**Comment by LegendAdmin** [comment]
Oh, I solved it. It was an internet problem.
