### ISSUE TITLE
V16-dev exception: GQL service unavailable

### ISSUE THREAD

**Issue by Oplikk** [DevilXD/TwitchDropsMiner#263]
V16 dev c2a5db8

```
20:16:38: Claimed bonus points: 50
20:16:38: Earned points for watching:  50, total: 7940
20:21:38: Earned points for watching:  10, total: 7950
20:23:14: Fatal error encountered:
20:23:14: 
20:23:14: Traceback (most recent call last):
20:23:14:   File "main.py", line 175, in main
20:23:14:   File "twitch.py", line 768, in run
20:23:14:   File "twitch.py", line 810, in _run
20:23:14:   File "twitch.py", line 1624, in fetch_inventory
20:23:14:   File "asyncio\tasks.py", line 611, in _wait_for_one
20:23:14:   File "twitch.py", line 1579, in fetch_campaigns
20:23:14:   File "twitch.py", line 1546, in gql_request
20:23:14: exceptions.MinerException: GQL error: [{'message': 'service unavailable', 'path': ['user', 'dropCampaign', 'allow', 'channels']}]
20:23:14: 
20:23:14: Exiting...
20:23:14: 
20:23:14: Application Terminated.
20:23:14: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Hello o/

https://github.com/DevilXD/TwitchDropsMiner/commit/e500569c332f68939f77faf80f41413e6db437d9 should fix this issue, and will become available once v16 releases. In the mean time, you can grab the latest fix from the master branch, or the pre-release dev build.
