### ISSUE TITLE
ERROR:	Exception in task

### ISSUE THREAD

**Issue by King-Thw** [DevilXD/TwitchDropsMiner#30]
hi bro,can u  tell me how to solve it ?thanks.
2022-07-12 23:34:43.944:	  ERROR:	Exception in task
Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1175, in _create_direct_connection
  File "aiohttp\connector.py", line 986, in _wrap_create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiohttp\client.py", line 535, in _request
  File "async_timeout\__init__.py", line 129, in __aexit__
  File "async_timeout\__init__.py", line 212, in _do_exit
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "twitch.py", line 833, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 539, in _request
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://twitch.tv/beast1k

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "utils.py", line 91, in wrapper
  File "twitch.py", line 402, in _watch_loop
  File "channel.py", line 338, in send_watch
  File "channel.py", line 213, in get_spade_url
  File "contextlib.py", line 171, in __aenter__
  File "twitch.py", line 841, in request
exceptions.RequestException: Ran out of attempts while handling a request: (method='GET', url='https://twitch.tv/beast1k', attempts=5, kwargs={})

**Comment by DevilXD** [comment]
Hello o/

Judging from experience, you're probably using a proxy. You'll need to specify your HTTP proxy URL on the application's `Settings` tab. If you're not using a proxy, then you somehow ended up not being able to reach Twitch - please verify that you can open Twitch's main page in your browser.

**Comment by King-Thw** [comment]
hi bro
I use a local reverse proxy, so what should I fill in?

**Comment by King-Thw** [comment]
hi bro
Why did I make such a mistake even without acting? It was normal for the software to make such a mistake, but the time would stop after a period of time, and it would still help me take the treasure box.

**Comment by DevilXD** [comment]
I'm not sure what you're trying to say. The application requires an information about your proxy setup if you do use one - without this, it's just going to not let you connect to Twitch properly. Is your proxy setup properly to allow for this connection? Are you putting in the correct URL?

**Comment by DevilXD** [comment]
Are you still having trouble with the setup? I don't know if this issue can be marked as solved or not. Did you get it to work?

**Comment by DevilXD** [comment]
I'm closing this because no further information was available. Please try out the newest `v12` and feel free to open another issue if you'd encounter anything like it again: https://github.com/DevilXD/TwitchDropsMiner/releases
