### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by Antwa-sensei253** [DevilXD/TwitchDropsMiner#303]
Hi, I am having this problem when running the program using "python main.py":
```css
0:50:14: Please log in to continue.
00:50:15: Enter this code on the Twitch's device activation page: SMJBHJZY
00:50:45: Fatal error encountered:
00:50:45: 
00:50:45: Traceback (most recent call last):
00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/main.py", line 175, in <module>
00:50:45:     loop.run_until_complete(client.run())
00:50:45:   File "/home/antwa/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
00:50:45:     return future.result()
00:50:45:            ^^^^^^^^^^^^^^^
00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/twitch.py", line 759, in run
00:50:45:     await self._run()
00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/twitch.py", line 801, in _run
00:50:45:     await self.fetch_inventory()
00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/twitch.py", line 1636, in fetch_inventory
00:50:45:     await self.gui.inv.add_campaign(campaign)
00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/gui.py", line 1291, in add_campaign
00:50:45:     campaign_image = await self._cache.get(campaign.image_url, size=(108, 144))
00:50:45:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/cache.py", line 99, in get
00:50:45:     img_hash = self._hash(image)
00:50:45:                ^^^^^^^^^^^^^^^^^
00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/cache.py", line 78, in _hash
00:50:45:     pixel_data = list(image.resize((10, 10), Image_module.ANTIALIAS).convert('L').getdata())
00:50:45:                                              ^^^^^^^^^^^^^^^^^^^^^^
00:50:45: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
00:50:45: 
00:50:45: Exiting...
00:50:45: 
00:50:45: Application Terminated.
00:50:45: Close the window to exit the application.

```
also when I try to run the gui.py I encounter the error above where " 00:50:45:   File "xxx/xxx/xxxx/xxx/TwitchDropsMiner-15/cache.py", line 78, in _hash
00:50:45:     pixel_data = list(image.resize((10, 10), Image_module.ANTIALIAS).convert('L').getdata())
00:50:45:                                              ^^^^^^^^^^^^^^^^^^^^^^
00:50:45: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'" is still the same.

I am running arch linux distro.

**Comment by Antwa-sensei253** [comment]
to   solve the problem just install this version using:
pip install Pillow==9.5.0
why this error occurs  is due to pillow lib is not using PIL.Image but using something different,
that is why  it is not working

**Comment by DevilXD** [comment]
To avoid problems, I recommend using a virtual Python environment and installing everything through the attached `requirements.txt` file. Pillow has already been pinned to version `<10` due to this exact issue over 3 months ago in https://github.com/DevilXD/TwitchDropsMiner/commit/562627e6579a6a9c3203ef51917f2bfdc3ea2d0b
