### ISSUE TITLE
GQL Error Report: 'context deadline exceeded'

### ISSUE THREAD

**Issue by Taizunz** [DevilXD/TwitchDropsMiner#317]
```
04:00:14: Claimed drop: EVE Online Retribution Malagrin SKIN (1/4)
04:00:30: Fatal error encountered:
04:00:30: 
04:00:30: Traceback (most recent call last):
04:00:30:   File "main.py", line 175, in main
04:00:30:   File "twitch.py", line 765, in run
04:00:30:   File "twitch.py", line 807, in _run
04:00:30:   File "twitch.py", line 1600, in fetch_inventory
04:00:30:   File "twitch.py", line 1548, in gql_request
04:00:30: exceptions.MinerException: GQL error: [{'message': 'context deadline exceeded'}]
04:00:30: 
04:00:30: Exiting...
04:00:30: 
04:00:30: Application Terminated.
04:00:30: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Hello. Is this a repeating error, or a single occurrence of it?

**Comment by Taizunz** [comment]
A single occurrence.

**Comment by DevilXD** [comment]
Thank you for your report. The cause has been determined to be an unstable internet connection to the Twitch server, and https://github.com/DevilXD/TwitchDropsMiner/commit/fc1f3ed70a4fb02e7ecf816b85e1cdae62b43bb7 has been pushed out to handle cases like this going forward, by repeating the request.
