### ISSUE TITLE
GQL Error Report: 'graphql: got nil for non-null "DropCampaignSelfEdge"'

### ISSUE THREAD

**Issue by Taizunz** [DevilXD/TwitchDropsMiner#322]
Single occurrence.
```
04:46:16: Earned points for watching:  50, total: 2160
04:46:27: Fatal error encountered:
04:46:27: 
04:46:27: Traceback (most recent call last):
04:46:27:   File "main.py", line 175, in main
04:46:27:   File "twitch.py", line 765, in run
04:46:27:   File "twitch.py", line 807, in _run
04:46:27:   File "twitch.py", line 1609, in fetch_inventory
04:46:27:   File "twitch.py", line 1548, in gql_request
04:46:27: exceptions.MinerException: GQL error: [{'message': 'graphql: got nil for non-null "DropCampaignSelfEdge"', 'path': ['currentUser', 'dropCampaigns', 51, 'self']}]
04:46:27: 
04:46:27: Exiting...
04:46:27: 
04:46:27: Application Terminated.
04:46:27: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Hello. This doesn't look right. Which version of the application are you using?

**Comment by Taizunz** [comment]
v16.dev.d892bc0

**Comment by DevilXD** [comment]
I see. This looks like an internal Twitch GQL error, nothing to do with the application itself. If it's only a single occurrence, I could try filtering it out, but otherwise, I think it can be disregarded for now. That being said, I guess it's best to keep this issue open for at least 2 weeks, to see if anyone else would run into this.
