### ISSUE TITLE
GUI starts but miner does not

### ISSUE THREAD

**Issue by designstorming** [DevilXD/TwitchDropsMiner#332]
**OS**: Windows 23H2 (22631.2428) x64

I have no idea what happened. After an update from 22H2 to 23H2, it just stopped working. I presume SSL something is missing from somewhere....

```bash
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 158, in main
  File "twitch.py", line 764, in run
  File "twitch.py", line 783, in _run
  File "twitch.py", line 1454, in get_auth
  File "twitch.py", line 515, in validate
  File "twitch.py", line 524, in _validate
  File "contextlib.py", line 181, in __aenter__
  File "twitch.py", line 1479, in request
  File "gui.py", line 2050, in coro_unless_closed
  File "aiohttp\client.py", line 1151, in send
  File "aiohttp\client.py", line 562, in _request
  File "aiohttp\connector.py", line 540, in connect
  File "aiohttp\connector.py", line 901, in _create_connection
  File "aiohttp\connector.py", line 1141, in _create_direct_connection
  File "aiohttp\connector.py", line 957, in _get_ssl_context
  File "aiohttp\connector.py", line 909, in _make_ssl_context
  File "ssl.py", line 751, in create_default_context
  File "ssl.py", line 575, in load_default_certs
  File "ssl.py", line 567, in _load_windows_store_certs
ssl.SSLError: not enough data: cadata does not contain a certificate (_ssl.c:4159)

Exiting...

Application Terminated.
Close the window to exit the application.
```

Edit: I have installed a fresh copy on my friend's computer and it works out of the box. Any help is appreciated ❤️

**Comment by designstorming** [comment]
Just in case someone encounters the same error:
1. Remove any application that installs unverified certificate (in my case "Citac elektronske licne karte (CELIK)".
2. Allow app in windows defender if it blocks it
