### ISSUE TITLE
Unable to init server

### ISSUE THREAD

**Issue by lyxlucky** [DevilXD/TwitchDropsMiner#357]
hello sir
I started the program on my cloud service and here is the output error message

> Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "main.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "twitch.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "gui.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pystray/__init__.py", line 64, in <module>
  File "pystray/__init__.py", line 56, in backend
  File "pystray/__init__.py", line 28, in appindicator
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pystray/_appindicator.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pystray/_util/gtk.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pystray/_util/notify_dbus.py", line 24, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace DBus not available
[3860] Failed to execute script 'main' due to unhandled exception!

**Comment by lyxlucky** [comment]
it's not working on linux server without gui?

**Comment by lyxlucky** [comment]
Does it run in a linux terminal?

**Comment by DevilXD** [comment]
Hello. This isn't a console application, but a desktop one. There's no CLI interface to it. If you're looking for something you can run on a server though, there are other projects out there that are more suited for your needs than this one.
