### ISSUE TITLE
AppImage requires python 3.8.

### ISSUE THREAD

**Issue by Techwolf** [DevilXD/TwitchDropsMiner#404]
Trying the appimage on my gentoo system that only has python 3.11.

```
Traceback (most recent call last):
  File "/tmp/.mount_TwitchSAXRx5/usr/src/main.py", line 26, in <module>
    from twitch import Twitch
  File "/tmp/.mount_TwitchSAXRx5/usr/src/twitch.py", line 38, in <module>
    from gui import GUIManager
  File "/tmp/.mount_TwitchSAXRx5/usr/src/gui.py", line 21, in <module>
    import pystray
  File "/tmp/.mount_TwitchSAXRx5/usr/lib/python3.8/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/tmp/.mount_TwitchSAXRx5/usr/lib/python3.8/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/tmp/.mount_TwitchSAXRx5/usr/lib/python3.8/site-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
  File "/tmp/.mount_TwitchSAXRx5/usr/lib/python3.8/site-packages/pystray/_appindicator.py", line 20, in <module>
    gi.require_version('Gtk', '3.0')
  File "/tmp/.mount_TwitchSAXRx5/usr/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

I have not tried the other type, PyInstaller.

I did manage to get it running by using hints in another bug to run the git version and had to use PYSTRAY_BACKEND=gtk

Is it possible to package all the python depends in AppImage so it can run on any linux system?

**Comment by DevilXD** [comment]
I'm assuming this one is solved by now.

**Comment by guihkx** [comment]
So, if I understand correctly, you do not have DBus installed? If that's the case, I'm not sure the systray can work without it...

As a last resort, you could try any of the other backends supported by pystray:

https://pystray.readthedocs.io/en/latest/usage.html#supported-backends

If that also doesn't work, then I'm out of ideas.

**Comment by DevilXD** [comment]
If this is related solely to the tray icon support, it could be a good idea to report this under the Pystray repo: https://github.com/moses-palmer/pystray

You'd need a good repro code for it though. I can write up something simple for you to test, if you'd like to go this route. Or you can write it yourself if you know how to. Or you can just link this project as reference. Up to you, really.
