### ISSUE TITLE
Properly handle GQL "service error"

### ISSUE THREAD

**Issue by DevilXD** [DevilXD/TwitchDropsMiner#417]
Most likely as part of the #220's rewrite.

**Comment by ridai260** [comment]
```
08:46:49: ERROR: Retrying a service error for DirectoryPage_Game
08:46:54: Fatal error encountered:
08:46:54: 
08:46:54: Traceback (most recent call last):
08:46:54:   File "twitch.py", line 1537, in get_live_streams
08:46:54:     response = await self.gql_request(
08:46:54:   File "twitch.py", line 1339, in gql_request
08:46:54:     raise GQLException(response_json['errors'])
08:46:54: exceptions.GQLException: [{'message': 'service error', 'path': ['game']}]
08:46:54: 
08:46:54: The above exception was the direct cause of the following exception:
08:46:54: 
08:46:54: Traceback (most recent call last):
08:46:54:   File "main.py", line 161, in main
08:46:54:     await client.run()
08:46:54:   File "twitch.py", line 589, in run
08:46:54:     await self._run()
08:46:54:   File "twitch.py", line 754, in _run
08:46:54:     new_channels.update(await self.get_live_streams(game, drops_enabled=True))
08:46:54:   File "twitch.py", line 1548, in get_live_streams
08:46:54:     raise MinerException(f"Game: {game.slug}") from exc
08:46:54: exceptions.MinerException: Game: diablo-iv
08:46:54: 
08:46:54: Exiting...
08:46:54: 
08:46:54: Application Terminated.
08:46:54: Close the window to exit the application.
```

Then I removed Diablo IV from the list:

```
08:48:53: ERROR: Retrying a service error for DirectoryPage_Game
08:48:59: ERROR: Retrying a service error for DirectoryPage_Game
08:49:04: Fatal error encountered:
08:49:04: 
08:49:04: Traceback (most recent call last):
08:49:04:   File "twitch.py", line 1537, in get_live_streams
08:49:04:     response = await self.gql_request(
08:49:04:   File "twitch.py", line 1339, in gql_request
08:49:04:     raise GQLException(response_json['errors'])
08:49:04: exceptions.GQLException: [{'message': 'service error', 'path': ['game']}]
08:49:04: 
08:49:04: The above exception was the direct cause of the following exception:
08:49:04: 
08:49:04: Traceback (most recent call last):
08:49:04:   File "main.py", line 161, in main
08:49:04:     await client.run()
08:49:04:   File "twitch.py", line 589, in run
08:49:04:     await self._run()
08:49:04:   File "twitch.py", line 754, in _run
08:49:04:     new_channels.update(await self.get_live_streams(game, drops_enabled=True))
08:49:04:   File "twitch.py", line 1548, in get_live_streams
08:49:04:     raise MinerException(f"Game: {game.slug}") from exc
08:49:04: exceptions.MinerException: Game: marvel-rivals
08:49:04: 
08:49:04: Exiting...
08:49:05: 
08:49:05: Application Terminated.
08:49:05: Close the window to exit the application.

```
Pulled the lastest yesterday and built the exe, was working fine until turning my pc on today to use it, immediate error.

**Comment by K4HVH** [comment]
I'm getting the same error, it used to only happen pretty infrequently, but now it happens basically every time I open the app. Running the latest pull with a fresh build. I can't get it to consistently do it though, which is making testing difficult

```
13:54:12: ERROR: Retrying a service error for DirectoryPage_Game
13:54:17: Fatal error encountered:
13:54:17: 
13:54:17: Traceback (most recent call last):
13:54:17:   File "twitch.py", line 1537, in get_live_streams
13:54:17:   File "twitch.py", line 1339, in gql_request
13:54:17: exceptions.GQLException: [{'message': 'service error', 'path': ['game']}]
13:54:17: 
13:54:17: The above exception was the direct cause of the following exception:
13:54:17: 
13:54:17: Traceback (most recent call last):
13:54:17:   File "main.py", line 161, in main
13:54:17:   File "twitch.py", line 589, in run
13:54:17:   File "twitch.py", line 754, in _run
13:54:17:   File "twitch.py", line 1548, in get_live_streams
13:54:17: exceptions.MinerException: Game: overwatch-2
13:54:17: 
13:54:17: Exiting...
13:54:18: 
13:54:18: Application Terminated.
13:54:18: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
This particular GQL operation's hash has been updated about 3 weeks ago, so if you haven't updated the miner in a while, I'd recommend doing so. Also, pretty much all "service error" cases are temporary and usually caused by Twitch changing things around, and will pass on it's own eventually. It can take anywhere from minutes to a few days in the worst case scenario, so you can just keep the miner off for a while, and then relaunch later. If there's some urgent drops you want to get, you'll need to watch in the browser, until Twitch resolves the error on their side.

On this topic though, I've been wondering if this error couldn't be handled the same way as a timeout would be. I remember there being some reasoning against it, but I can't find it now.

**Comment by gbzret4d** [comment]
Would it be possible to implement an autorestart function, so if the error occurs it restarts itself?

**Comment by DevilXD** [comment]
@gbzret4d If you'd use the search function, you'd learn that this was suggested before on multiple occasions, and I've already explained why this is a bad idea. See #147.

**Comment by K4HVH** [comment]
@DevilXD How do you propose it gets fixed then though? It happens consistently ~every hour for me, and judging by the popularity of this bug report, many others too.

I know you say it's Twitch's fault, but it's a problem nonetheless

**Comment by DevilXD** [comment]
@K4HVH This issue happens since the beginning of 2024, as you can tell from the age of this issue. We cannot talk about "consistency" here though - one day it'll happen every 10 minutes, another it won't happen at all for a whole month. All of it depends on the stability of Twitch drops service, and this can change as Twitch continues to work on their website. Is it a problem? Sure. Is it bad enough to consider it a critical issue? Not really, no. Just like in the past cases, it'll most likely pass on it's own either today or tomorrow, and this issue will be forgotten for another month again.

As far as handling it goes, I've tracked down some reasoning here: https://github.com/Windows200000/TwitchDropsMiner-updated/issues/86#issuecomment-2143585419. It's not simple, especially since some requests in the miner are executed concurrently, so not only it'd end up looping too fast relative to the scope of the issue, but it'd also (potentially) end up doing so in parallel with several other requests. These down times range from seconds to hours, and there's no way to predict them, so the solution would have to scale it's backoff time according to the error encountered, something that it currently doesn't do.

The biggest issue is that the current miner's code isn't really ready for a change like this, and I basically have an idea what needs to be done, but struggle to figure out how to implement it in the current code. It feels like the first change that needs to happen instead, would be restructuring the logging logic, so that the "forever looping" case wouldn't go unnoticed and would be easily recognizable.

**Comment by gbzret4d** [comment]
But i guess its not normal that it happens for me for over 1 week now multiple times per day. Twitch status dont show problems when for me the error occurs. Tried it on multiple systems with different settings.

**Comment by DevilXD** [comment]
To be fair, I don't really know what qualifies as "normal" in this case. I've personally encountered the issue like 4 times total, 2 of those times being quite recent, and the other ones being far in the past. As far as I've seen others dealing with it, it really just comes and goes about once a month or two, and lasts for an undefined amount of time. The true reasons and timeframe behind it happening are known only to Twitch developers, so we can only speculate how long will it last this time.

**Comment by gbzret4d** [comment]
Ok so the problem occurs for everyone atm? This isnt clear for me.

**Comment by DevilXD** [comment]
The error occurs only during inventory loading/reload, only if the drops service happens to go out in that exact moment, and only if the miner is going to actually mine anything. Since the reloads happen only once every hour, there's a chance a miner instance won't run into the issue, if the service goes down right in between reloads. You can scroll up to see all of the duplicate issues of it happening to others over the past two years, yet as I've said before, it only happened about 4 times to me, and none today too. And I've had the miner running for about 12 hours straight by now:

```
10:49:59: No active campaigns to mine drops for. Waiting for an active campaign...
11:50:02: No active campaigns to mine drops for. Waiting for an active campaign...
12:50:06: No active campaigns to mine drops for. Waiting for an active campaign...
13:50:09: No active campaigns to mine drops for. Waiting for an active campaign...
14:50:14: No active campaigns to mine drops for. Waiting for an active campaign...
15:50:17: No active campaigns to mine drops for. Waiting for an active campaign...
16:50:21: No active campaigns to mine drops for. Waiting for an active campaign...
17:50:24: No active campaigns to mine drops for. Waiting for an active campaign...
18:50:29: No active campaigns to mine drops for. Waiting for an active campaign...
19:50:33: No active campaigns to mine drops for. Waiting for an active campaign...
20:50:37: No active campaigns to mine drops for. Waiting for an active campaign...
21:50:40: No active campaigns to mine drops for. Waiting for an active campaign...
22:50:45: No active campaigns to mine drops for. Waiting for an active campaign...
```

That being said, I also had nothing to mine today, so that might also be why. I have about 5 games on the priority list. Others having 10+ games might be having more trouble.

I'm still thinking about a good way of tackling this, and haven't been able to come up with much. I have tomorrow's day off, so hopefully I can push this forward somehow.

**Comment by gbzret4d** [comment]
For me its happening every hour since multiple days thats why im asking. How to prevent this?

**Comment by DevilXD** [comment]
We cannot prevent it directly. It's the Twitch service going up and down that causes the issue, so the direct solution for this is up to Twitch developers.

The miner has to be able to deal with it though, and as I've said, I'm working on it right now. All you can do, is just wait patiently. This issue is 2 years old by now, so don't expect a quick solution, as I've said, it's a complex one to deal with.

If it happens for you frequently, it may be best for you to just ditch the miner and get the drops the normal way instead. Although as #841 shows, that may also be quite hard to do. Otherwise, it's more of the usual thing - close it off, wait some time, and then restart later on.

**Comment by gbzret4d** [comment]
i made a small sctip which is downloading updates from your repo, kill the process and restarts the miner. With a crontab its possible to use it as autorestart so people dont have to look after some hours to find out twitchdropsminer has crashed and wasnt farming at all.

```
#!/bin/bash
#----------------------------------------------------
# Script: restart_twitchdrops.sh
# Purpose: Update and restart Twitch Drops Miner by DevilXD
#          with self-update support from GitHub.
# Usage:
#   ./restart_twitchdrops.sh
# Requirements:
#   - wget, unzip, rsync, sha1sum installed
# Notes:
#   - Runs as current user without hardcoded username.
#   - Assumes Twitch Drops Miner installed at ~/Desktop/devilxd/Twitch Drops Miner
#----------------------------------------------------

set -euo pipefail

# Detect current user and home directory
USER=$(id -un)
USER_HOME=$(eval echo "~$USER")

SCRIPT_NAME=$(basename "$0")

# --- GITHUB URLs ---
GITHUB_REPO_RAW_URL="https://raw.githubusercontent.com/gbzret4d/DevilXD-TwitchDropsMiner-restart-skript/main/$SCRIPT_NAME"
GITHUB_API_LATEST_COMMIT="https://api.github.com/repos/gbzret4d/DevilXD-TwitchDropsMiner-restart-skript/commits/main"

# Paths and URLs
PROGRAM_PATH="$USER_HOME/Desktop/devilxd/Twitch Drops Miner/Twitch Drops Miner (by DevilXD)"
DOWNLOAD_DIR="$USER_HOME/Downloads"
ZIP_URL="https://github.com/DevilXD/TwitchDropsMiner/releases/download/dev-build/Twitch.Drops.Miner.Linux.PyInstaller-x86_64.zip"
ZIP_NAME="$DOWNLOAD_DIR/Twitch.Drops.Miner.Linux.PyInstaller-x86_64.zip"
TMP_EXTRACT_DIR="/tmp/twitchdropsminer_update_tmp"
TARGET_DIR="$USER_HOME/Desktop/devilxd/Twitch Drops Miner"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

self_update() {
  # Calculate local script SHA1
  local_sha=$(sha1sum "$0" | awk '{print $1}')

  # Get latest commit SHA from GitHub API
  remote_sha=$(wget -qO- "$GITHUB_API_LATEST_COMMIT" | grep -m1 '"sha"' | cut -d '"' -f4)

  if [ -z "$remote_sha" ]; then
    log "WARNING: Could not get remote latest commit SHA; skipping self-update."
    return
  fi

  # Download remote script for SHA comparison
  remote_tmp="/tmp/${SCRIPT_NAME}.remote"
  if ! wget -qO "$remote_tmp" "$GITHUB_REPO_RAW_URL"; then
    log "WARNING: Could not download latest script for self-update."
    rm -f "$remote_tmp"
    return
  fi

  remote_file_sha=$(sha1sum "$remote_tmp" | awk '{print $1}')

  if [ "$local_sha" != "$remote_file_sha" ]; then
    log "Newer script version found on GitHub. Updating script..."
    cp "$remote_tmp" "$0"
    chmod +x "$0"
    rm -f "$remote_tmp"
    log "Script updated, restarting..."
    exec "$0" "$@"
    exit 0
  else
    log "Script already up to date."
    rm -f "$remote_tmp"
  fi
}

self_update

log "Starting Twitch Drops Miner update process..."

# Check for required commands
for cmd in wget unzip rsync sha1sum; do
  if ! command -v "$cmd" >/dev/null; then
    log "ERROR: Required command '$cmd' not found. Please install it."
    exit 1
  fi
done

# Stop running Twitch Drops Miner processes gracefully
log "Stopping running Twitch Drops Miner processes..."
pids=$(pgrep -f "Twitch Drops Mi" || true)

if [ -n "$pids" ]; then
  for pid in $pids; do
    kill "$pid" && log "Sent SIGTERM to process $pid." || {
      log "Failed SIGTERM, trying SIGKILL on process $pid."
      kill -9 "$pid" || log "Failed killing process $pid."
    }
  done

  # Wait up to 10 seconds for processes to exit
  for i in $(seq 1 10); do
    if ! pgrep -f "Twitch Drops Mi" >/dev/null; then
      log "All Twitch Drops Miner processes terminated."
      break
    fi
    sleep 1
  done

  if pgrep -f "Twitch Drops Mi" >/dev/null; then
    log "Processes still alive after SIGTERM, applying SIGKILL."
    pkill -9 -f "Twitch Drops Mi"
  fi
else
  log "No Twitch Drops Miner processes found."
fi

# Prepare temporary directory for extraction
log "Creating temporary directory: $TMP_EXTRACT_DIR"
rm -rf "$TMP_EXTRACT_DIR"
mkdir -p "$TMP_EXTRACT_DIR"

# Download latest Twitch Drops Miner ZIP archive
log "Downloading latest Twitch Drops Miner release..."
wget -O "$ZIP_NAME" "$ZIP_URL" || { log "ERROR: Download failed!"; exit 1; }

# Extract archive to temporary directory
log "Unpacking archive..."
unzip -q "$ZIP_NAME" -d "$TMP_EXTRACT_DIR" || { log "ERROR: Unzip failed!"; exit 1; }

# Backup existing installation files (except cookies.jat & settings.json)
BACKUP_DIR="$TARGET_DIR/backup_$(date '+%Y%m%d_%H%M%S')"
log "Backing up existing files to $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
rsync -a --exclude='cookies.jat' --exclude='settings.json' "$TARGET_DIR/" "$BACKUP_DIR/"

# Copy new files into target directory excluding cookies/settings
log "Copying new files to $TARGET_DIR"
rsync -a --exclude='cookies.jat' --exclude='settings.json' "$TMP_EXTRACT_DIR/Twitch Drops Miner/" "$TARGET_DIR/"

# Clean up
log "Cleaning up temporary files and downloads..."
rm -rf "$TMP_EXTRACT_DIR"
rm -f "$ZIP_NAME"

# Determine DISPLAY and XAUTHORITY for starting GUI app
DISPLAY=$(pgrep -u "$USER" -a | grep -o 'DISPLAY=:[0-9]\+' | head -n1 | cut -d= -f2 || true)
if [ -z "$DISPLAY" ]; then
  pid_xorg=$(pgrep -u "$USER" Xorg | head -n1 || true)
  if [ -n "$pid_xorg" ]; then
    DISPLAY=$(tr '\0' '\n' < /proc/"$pid_xorg"/environ | grep "^DISPLAY=" | cut -d= -f2 || true)
  fi
fi
DISPLAY=${DISPLAY:-:12}

XAUTHORITY="$USER_HOME/.Xauthority"
if [ ! -f "$XAUTHORITY" ]; then
  log "WARNING: XAUTHORITY file not found ($XAUTHORITY)"
fi

export DISPLAY
export XAUTHORITY

log "Starting Twitch Drops Miner with DISPLAY=$DISPLAY and XAUTHORITY=$XAUTHORITY"

if [ ! -x "$PROGRAM_PATH" ]; then
  log "ERROR: Program executable not found or not executable: $PROGRAM_PATH"
  exit 1
fi

nohup "$PROGRAM_PATH" >> "$TARGET_DIR/twitchdropsminer.log" 2>&1 &

log "Update and restart process complete."

```

**Comment by DevilXD** [comment]
@gbzret4d Mindlessly restarting the miner in this case is not a solution. This error can literally last for hours, and restarting it will just spam the Twitch servers with errors, most likely contributing to the demise of this project. For this reason specifically, I don't support it. You can see all project goals here: https://github.com/DevilXD/TwitchDropsMiner#project-goals

On the topic of this issue though, I've spent quite some time thinking about how I can tackle it the right way, and unfortunately there is no way to do it in a clean manner in the current version of the miner. I now know why this was tagged as part of the rewrite - it's because the miner's internals are not ready for a sudden loss of information from Twitch, that can last for an unspecified amount of time. For the miner to support this error properly, the state cannot be thrown out on every reload - which is what currently happens. Thus, without a rewrite, the only other way is to add this error to the usual error handler, which would end up spamming the GQL service with errors, over and over. This is only marginally better than a total restart (unless there's a long enough time given), and still not good enough of a solution.

**Comment by gbzret4d** [comment]
> [@gbzret4d](https://github.com/gbzret4d) Mindlessly restarting the miner in this case is not a solution. This error can literally last for hours, and restarting it will just spam the Twitch servers with errors, most likely contributing to the demise of this project. For this reason specifically, I don't support it. You can see all project goals here: https://github.com/DevilXD/TwitchDropsMiner#project-goals
> 
> On the topic of this issue though, I've spent quite some time thinking about how I can tackle it the right way, and unfortunately there is no way to do it in a clean manner in the current version of the miner. I now know why this was tagged as part of the rewrite - it's because the miner's internals are not ready for a sudden loss of information from Twitch, that can last for an unspecified amount of time. For the miner to support this error properly, the state cannot be thrown out on every reload - which is what currently happens. Thus, without a rewrite, the only other way is to add this error to the usual error handler, which would end up spamming the GQL service with errors, over and over. This is only marginally better than a total restart (unless there's a long enough time given), and still not good enough of a solution.

Possible to add that TwitchDropsMiner closes itself after a crash? Is this possible to add such option, so a script could restart it if theres no open process.

**Comment by DevilXD** [comment]
@gbzret4d   **No.** I've already explained why automatic restart is not supported, and I won't be doing anything to help automate it either. If you want such functionality, you'll need to implement it yourself.

Besides, again, if you just mindlessly restart the miner automatically on any error, you will miss what the error even was (unreported errors cannot be fixed), the miner won't be doing what it's supposed to do (because it'll keep restarting instead), and you'll end up bringing this project up on the Twitch's "annoying bot" list, encouraging Twitch to implement even more anti-bot measures than we already have.

This is what happened in the past. This is why the web client now has Kasada protection. This is why the old/normal login method have had stopped working, forcing the miner to implement Chromedriver login, and then that had stopped working too. Out of the four possible client IDs, this current one is the only one that still somehow works, while the others have had their functionality taken away or were blocked down, and became unusable. There were so many changes that have killed this project entirely, making it unusable for days, weeks or even months (IIRC longest down time was like 4 months), and it's also the reason why I had to keep fixing this existing mess, instead of being able to work on the next stable version. It's been 3+ years and it's still nowhere in sight. I'm getting tired of it.

This thing was always intended to be a tool, that you just open and use when you need to, and then turn off at the end of the day. If there is an unrecoverable error, **you** are the one responsible for figuring out what happened, and managing a restart if applicable. In this very case, an immediate restart often has zero sense, as the Twitch API failures can last for hours, and throwing unnecessary errors at the Twitch API is the last thing I want.

Still want it to restart automatically? **Implement it yourself.** I want nothing to do with it. I won't stop you (I can't since this project is open source), but I won't help you either. I really don't want to have to explain all of this again. The project goals are already quite clear on all this for a reason. It all has a reason behind it.

To fix this error, the miner has to be rewritten entirely, to allow taking into account a case where the Twitch API becomes unavailable. This was nowhere on the table, back when I was coming up how this thing is supposed to work. The current code just isn't ready for it. Every solution I was able to come up with either ends up with the miner spamming Twitch (which we don't want), or just ends up with the miner ending up with an invalid/empty state. All you have to do, is patiently wait for the rewrite to eventually happen. That's it.

**Comment by gbzret4d** [comment]
Anything we could do to help you if someone like myself is not a guy who can code stuff?

**Comment by DevilXD** [comment]
Well... I'd really like to work together with at least one more person on this. Coding knowledge isn't required as much, as me just finding enough time and mental power for this, and having the whole idea well thought out. Both of those things are spotty right now. My work environment has improved a bit ago, and I'm no longer constantly exhausted at least. Now I need to come up with a structure to all this. This is the most important part of every project, as messing up the base can and will lead to situations like this one, where properly implementing a fix isn't really possible without having the right backbone that can work with it.

The biggest problem seems to be that I've lost the passion for this project, the very one that was pushing me all along to make the existence of this project possible. I've seen so much misuse and/or straight up abuse, I've considered closing down all support on this already. Still though, I want to work on making the rewrite possible.

**Comment by Trebossalol** [comment]
> Well... I'd really like to work together with at least one more person on this. Coding knowledge isn't required as much, as me just finding enough time and mental power for this, and having the whole idea well thought out. Both of those things are spotty right now. My work environment has improved a bit ago, and I'm no longer constantly exhausted at least. Now I need to come up with a structure to all this. This is the most important part of every project, as messing up the base can and will lead to situations like this one, where properly implementing a fix isn't really possible without having the right backbone that can work with it.
> 
> The biggest problem seems to be that I've lost the passion for this project, the very one that was pushing me all along to make the existence of this project possible. I've seen so much misuse and/or straight up abuse, I've considered closing down all support on this already. Still though, I want to work on making the rewrite possible.

I am interested in supporting you in this project regarding the web UI.
I’ve been a hobby dev for years and I used this repo/docker image for quite some time.
If this is an option for you, I could create a web server written in JavaScript(nextjs Framework) storing all settings in a database. You can develop the backend/miner logic.
If you are interested in this you can write me on discord to discuss further: trebossa

**Comment by DevilXD** [comment]
@Trebossalol This has nothing to do with the topic of this issue, so I moved it to a separate one: #919. Please see/continue there from now on.

**Comment by drachescript** [comment]
would guess this is the same error?
03:19:50: ERROR: Retrying a service error for DirectoryPage_Game
03:19:55: Fatal error encountered:
03:19:55: 
03:19:55: Traceback (most recent call last):
03:19:55:   File "twitch.py", line 1540, in get_live_streams
03:19:55:   File "twitch.py", line 1342, in gql_request
03:19:55: exceptions.GQLException: [{'message': 'service error', 'path': ['game']}]
03:19:55: 
03:19:55: The above exception was the direct cause of the following exception:
03:19:55: 
03:19:55: Traceback (most recent call last):
03:19:55:   File "main.py", line 161, in main
03:19:55:   File "twitch.py", line 589, in run
03:19:55:   File "twitch.py", line 754, in _run
03:19:55:   File "twitch.py", line 1551, in get_live_streams
03:19:55: exceptions.MinerException: Game: palia
03:19:55: 
03:19:55: Exiting...
03:19:56: 
03:19:56: Application Terminated.
03:19:56: Close the window to exit the application.
