### ISSUE TITLE
When the software is opened, an error occurs and cannot be used.

### ISSUE THREAD

**Issue by luyurun** [DevilXD/TwitchDropsMiner#419]
An error occurs when opening the software. I have re-downloaded the software and tried to regenerate the configuration file, but the problem seems to remain the same.

```
20:58:04: Fatal error encountered:
20:58:04: 
20:58:04: Traceback (most recent call last):
20:58:04:   File "aiohttp\connector.py", line 992, in _wrap_create_connection
20:58:04:   File "asyncio\base_events.py", line 1090, in create_connection
20:58:04:   File "asyncio\base_events.py", line 1120, in _create_connection_transport
20:58:04:   File "asyncio\sslproto.py", line 534, in data_received
20:58:04:   File "asyncio\sslproto.py", line 188, in feed_ssldata
20:58:04:   File "ssl.py", line 945, in do_handshake
20:58:04: ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
20:58:04: 
20:58:04: The above exception was the direct cause of the following exception:
20:58:04: 
20:58:04: Traceback (most recent call last):
20:58:04:   File "main.py", line 158, in main
20:58:04:   File "twitch.py", line 764, in run
20:58:04:   File "twitch.py", line 783, in _run
20:58:04:   File "twitch.py", line 1469, in get_auth
20:58:04:   File "twitch.py", line 515, in validate
20:58:04:   File "twitch.py", line 524, in _validate
20:58:04:   File "contextlib.py", line 181, in __aenter__
20:58:04:   File "twitch.py", line 1494, in request
20:58:04:   File "gui.py", line 2050, in coro_unless_closed
20:58:04:   File "aiohttp\client.py", line 1174, in throw
20:58:04:   File "aiohttp\client.py", line 574, in _request
20:58:04:   File "aiohttp\connector.py", line 544, in connect
20:58:04:   File "aiohttp\connector.py", line 911, in _create_connection
20:58:04:   File "aiohttp\connector.py", line 1235, in _create_direct_connection
20:58:04:   File "aiohttp\connector.py", line 1204, in _create_direct_connection
20:58:04:   File "aiohttp\connector.py", line 994, in _wrap_create_connection
20:58:04: aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host m.twitch.tv:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]
20:58:04: 
20:58:04: Exiting...
20:58:04: 
20:58:04: Application Terminated.
20:58:04: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Hello o/

This is an issue with your computer, not the miner. Details can be found here:

https://github.com/DevilXD/TwitchDropsMiner/issues/386#issuecomment-1854345004
https://github.com/DevilXD/TwitchDropsMiner/issues/386#issuecomment-1869692063

Closing this as a duplicate.
