### ISSUE TITLE
exceptions.MinerException: Game: stream-raiders

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [DevilXD/TwitchDropsMiner#443]
```
19:57:42: Fatal error encountered:
19:57:42: 
19:57:42: Traceback (most recent call last):
19:57:42:   File "twitch.py", line 1714, in get_live_streams
19:57:42:   File "twitch.py", line 1570, in gql_request
19:57:42: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
19:57:42: 
19:57:42: The above exception was the direct cause of the following exception:
19:57:42: 
19:57:42: Traceback (most recent call last):
19:57:42:   File "main.py", line 158, in main
19:57:42:   File "twitch.py", line 768, in run
19:57:42:   File "twitch.py", line 920, in _run
19:57:42:   File "twitch.py", line 1725, in get_live_streams
19:57:42: exceptions.MinerException: Game: stream-raiders
19:57:42: 
19:57:42: Exiting...
19:57:42: 
19:57:42: Application Terminated.
19:57:42: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Hello. This sounds like a rollout of a new `DirectoryPage_Game` sha256 of the GQL operation responsible for fetching live channels. This will likely keep popping up for more and more people over time. Once I get my hands on the new sha256, I'll update it in the miner.

**Comment by RandomStrangerOnTheInternet** [comment]
The issue didn't occur anymore, seems to have resolved itself. You can close this issue if needed, or leave it open for future updates.

**Comment by DevilXD** [comment]
This should now be solved via https://github.com/DevilXD/TwitchDropsMiner/commit/2bd2845790a97fd72058c72cc0164d852df9feae in the latest master build.

**Comment by Taizunz** [comment]
This error appears to have resurfaced.

```
13:16:22: Cannot connect to Twitch, retrying in 2 seconds...
13:16:32: Fatal error encountered:
13:16:32: 
13:16:32: Traceback (most recent call last):
13:16:32:   File "twitch.py", line 1519, in get_live_streams
13:16:32:   File "twitch.py", line 1350, in gql_request
13:16:32: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
13:16:32: 
13:16:32: The above exception was the direct cause of the following exception:
13:16:32: 
13:16:32: Traceback (most recent call last):
13:16:32:   File "main.py", line 153, in main
13:16:32:   File "twitch.py", line 570, in run
13:16:32:   File "twitch.py", line 727, in _run
13:16:32:   File "twitch.py", line 1530, in get_live_streams
13:16:32: exceptions.MinerException: Game: palia
13:16:32: 
13:16:32: Exiting...
```

This was on commit dc48860 which I see is 2 commits behind. Not sure if the new commits fix it, but I'll update either way.
