### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by FruitJelliesGD** [DevilXD/TwitchDropsMiner#472]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/93989484/7cbc93f4-a680-4938-87cf-7d4b30e9c8d2)
use dev-build [https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build](:https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build)
`Traceback (most recent call last):
  File "main.py", line 196, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "main.py", line 152, in main
  File "twitch.py", line 629, in __init__
  File "gui.py", line 1982, in __init__
ctypes.ArgumentError: argument 1: OverflowError: int too long to convert
`
System: Windows 10

**Comment by Windows200000** [comment]
https://github.com/DevilXD/TwitchDropsMiner/issues/462#issuecomment-2116078692

**Comment by DevilXD** [comment]
Does restarting your PC fix the problem? Also, which translation are you using?
