### ISSUE TITLE
Cannot start on arch linux

### ISSUE THREAD

**Issue by wray-lee** [DevilXD/TwitchDropsMiner#477]
Logs as follows

```bash
Traceback (most recent call last):
  File "main.py", line 196, in <module>
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "main.py", line 152, in main
  File "twitch.py", line 630, in __init__
  File "gui.py", line 2020, in __init__
  File "gui.py", line 2228, in set_theme
  File "tkinter/ttk.py", line 522, in theme_use
_tkinter.TclError: can't find package ttk::theme::vista
[25710] Failed to execute script 'main' due to unhandled exception!
```

**Comment by guihkx** [comment]
But TDM doesn't even use the Vista theme, it uses the Classic one...

Did you manually change it?

**Comment by wray-lee** [comment]
> But TDM doesn't even use the Vista theme, it uses the Classic one...
> 
> Did you manually change it?

My fault. I am using a fork repo of this project. This is the error of that version.
