### ISSUE TITLE
Got fatal error 

### ISSUE THREAD

**Issue by LoneKnightz** [DevilXD/TwitchDropsMiner#49]
There is an error when this software going to claim : 

Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 170, in run
  File "twitch.py", line 228, in _run
  File "inventory.py", line 191, in claim
  File "inventory.py", line 109, in claim
  File "inventory.py", line 130, in _claim
KeyError: 'data'

Thanks

**Comment by DevilXD** [comment]
Hello o/

Which version are you using? There's an experimental `v13` available in #40 that you can try. `v12` is going to report errors like these until you upgrade.
