### ISSUE TITLE
GQL error: [{'message': 'PersistedQueryNotFound'}]

### ISSUE THREAD

**Issue by LeaLangley** [DevilXD/TwitchDropsMiner#520]
Version: 9768635
```
20:24:56: Fatal error encountered:
20:24:56: 
20:24:56: Traceback (most recent call last):
20:24:56:   File "main.py", line 153, in main
20:24:56:   File "twitch.py", line 570, in run
20:24:56:   File "twitch.py", line 620, in _run
20:24:56:   File "twitch.py", line 1428, in fetch_inventory
20:24:56:   File "asyncio\tasks.py", line 571, in _wait_for_one
20:24:56:   File "twitch.py", line 1383, in fetch_campaigns
20:24:56:   File "twitch.py", line 1350, in gql_request
20:24:56: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
```

**Comment by gibbed** [comment]
I commented over in https://github.com/Windows200000/TwitchDropsMiner-updated/issues/154#issuecomment-2243579643 too.

Looking at the request from the miner vs Twitch itself, it looks like the `sha256Hash` for the `DropCampaignDetails` persisted query has changed:

Old:

```json
{"persistedQuery":{"version":1,"sha256Hash":"e5916665a37150808f8ad053ed6394b225d5504d175c7c0b01b9a89634c57136"}}
```

New:

```json
{"persistedQuery":{"version":1,"sha256Hash":"e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54"}}
```

**Comment by Windows200000** [comment]
yup, the new one is `e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54` you can change it in `constants.py` if you search `DropCampaignDetails`

**Comment by hifocus** [comment]
Can confirm this resolves https://github.com/DevilXD/TwitchDropsMiner/issues/138#issuecomment-2243548782

**Comment by DevilXD** [comment]
Unfortunately, this is a duplicate of #519. Fortunately, it should already be fixed by the time you see this, just grab the latest master build.
