### ISSUE TITLE
KeyError: 'children'

### ISSUE THREAD

**Issue by SlorRy** [DevilXD/TwitchDropsMiner#540]
Traceback (most recent call last):
File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/main.py", line 198, in
asyncio.run(main())
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/main.py", line 154, in main
client = Twitch(settings)
^^^^^^^^^^^^^^^^
File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/twitch.py", line 630, in init
self.gui = GUIManager(self)
^^^^^^^^^^^^^^^^
File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/gui.py", line 1977, in init
sublayout["children"] = sublayout["children"][0][1]["children"]
~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'children'

**Comment by DevilXD** [comment]
Hello,

None of the traceback makes any sense. You are most likely using a version of the miner I don't support. Please make sure you're reporting this issue in the right place, because this isn't one. If you've downloaded it from a different place, that's where you should be reporting this instead, not here.
