### ISSUE TITLE
Twitch considers this miner as a "Bad Bot"

### ISSUE THREAD

**Issue by LoneKnightz** [DevilXD/TwitchDropsMiner#56]
I received this error today.  I used the newest code from github (downloaded 3 days ago). 
I tried to delete cookie but error existed.  
Error is below: 
Fatal error encountered:

Traceback (most recent call last):
  File "D:\Google Drive\software\Twitch Drops Miner\TwitchDropsMiner-master\main.py", line 169, in <module>
    loop.run_until_complete(client.run())
  File "C:\Users\zhang\.conda\envs\twitch\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Google Drive\software\Twitch Drops Miner\TwitchDropsMiner-master\twitch.py", line 402, in run
    await self._run()
  File "D:\Google Drive\software\Twitch Drops Miner\TwitchDropsMiner-master\twitch.py", line 422, in _run
    auth_state = await self.get_auth()
  File "D:\Google Drive\software\Twitch Drops Miner\TwitchDropsMiner-master\twitch.py", line 965, in get_auth
    await self._auth_state.verify()
  File "D:\Google Drive\software\Twitch Drops Miner\TwitchDropsMiner-master\twitch.py", line 192, in verify
    await self._verify()
  File "D:\Google Drive\software\Twitch Drops Miner\TwitchDropsMiner-master\twitch.py", line 270, in _verify
    raise MinerException(
exceptions.MinerException: Twitch considers this miner as a "Bad Bot". Try deleting the cookie file and try again.

Exiting...

Thanks for your help

**Comment by xmhyysd** [comment]
It seems that I am not alone .     :)

**Comment by DevilXD** [comment]
Hello o/

I kinda saw this coming eventually. Please stay in #40 where you've got the dev version from though, as that's the thread dedicated to the issue specifically. If you've got a traceback, please post it there instead.
