### ISSUE TITLE
If you set as ending soonest with no priority or exclusion games, it instatly crashes

### ISSUE THREAD

**Issue by NicoPlaysThings** [DevilXD/TwitchDropsMiner#564]
Here are the logs.

17:49:03: Fatal error encountered:
17:49:03: 
17:49:03: Traceback (most recent call last):
17:49:03:   File "main.py", line 155, in main
17:49:03:   File "twitch.py", line 587, in run
17:49:03:   File "twitch.py", line 747, in _run
17:49:03:   File "twitch.py", line 1625, in bulk_check_online
17:49:03: TypeError: 'NoneType' object is not subscriptable
17:49:03: 
17:49:03: Exiting...
17:49:04: 
17:49:04: Application Terminated.
17:49:04: Close the window to exit the application.

**Comment by DevilXD** [comment]
Duplicate of #558.

Add Ravendawn to the exclude list for now.
