### ISSUE TITLE
Program error.  Unable to claim the treasure box automatically.

### ISSUE THREAD

**Issue by jldhrj** [DevilXD/TwitchDropsMiner#57]
Program error.

Unable to claim the treasure box automatically.

Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 170, in run
  File "twitch.py", line 228, in _run
  File "inventory.py", line 191, in claim
  File "inventory.py", line 109, in claim
  File "inventory.py", line 130, in _claim
KeyError: 'data'

Exiting...

Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment]
Hello o/

This is know. Please refer to #40.
