### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Miollnir** [DevilXD/TwitchDropsMiner#58]
when i try to login it gives me this error:
 
Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 170, in run
  File "twitch.py", line 186, in _run
  File "twitch.py", line 827, in check_login
  File "twitch.py", line 801, in _login
exceptions.LoginException: Oops! We encountered an unexpected error. Please try again.

Exiting...

Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment]
@Miollnir Please refer to #40
