### ISSUE TITLE
Broken login

### ISSUE THREAD

**Issue by tiilopes** [DevilXD/TwitchDropsMiner#59]
Please log in to continue.
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 170, in run
  File "twitch.py", line 186, in _run
  File "twitch.py", line 827, in check_login
  File "twitch.py", line 801, in _login
exceptions.LoginException: Oops! We encountered an unexpected error. Please try again.

Exiting...

Application Terminated.
Close the window to exit the application.

Can someone help me?

**Comment by DevilXD** [comment]
Hello o/

This is already known. Please refer to #40 for further information.
