### ISSUE TITLE
Fatal Error after Login

### ISSUE THREAD

**Issue by Shazgul** [DevilXD/TwitchDropsMiner#60]
```
Fatal error encountered:

Traceback (most recent call last):
  File "E:\Twitch Drops\Twitch Drops Miner\main.py", line 169, in <module>
    loop.run_until_complete(client.run())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\Twitch Drops\Twitch Drops Miner\twitch.py", line 418, in run
    await self._run()
  File "E:\Twitch Drops\Twitch Drops Miner\twitch.py", line 438, in _run
    auth_state = await self.get_auth()
  File "E:\Twitch Drops\Twitch Drops Miner\twitch.py", line 981, in get_auth
    await self._auth_state.validate()
  File "E:\Twitch Drops\Twitch Drops Miner\twitch.py", line 198, in validate
    await self._validate()
  File "E:\Twitch Drops\Twitch Drops Miner\twitch.py", line 226, in _validate
    self.access_token = await self._login()
  File "E:\Twitch Drops\Twitch Drops Miner\twitch.py", line 170, in _login
    raise LoginException(login_response["error"])
exceptions.LoginException: Oops! We encountered an unexpected error. Please try again.

Exiting...
```

**Comment by DevilXD** [comment]
Hello o/

Please check out the "Important notice!" section of the [README.md](https://github.com/DevilXD/TwitchDropsMiner/blob/master/README.md) file, as well as issue #40.
