### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by LaoMingZi** [DevilXD/TwitchDropsMiner#61]
Please log in to continue.
Fatal error encountered:

Traceback (most recent call last):
  File "E:\TwitchDropsMiner-master\main.py", line 169, in <module>
    loop.run_until_complete(client.run())
  File "E:\Python3.8\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:\TwitchDropsMiner-master\twitch.py", line 418, in run
    await self._run()
  File "E:\TwitchDropsMiner-master\twitch.py", line 438, in _run
    auth_state = await self.get_auth()
  File "E:\TwitchDropsMiner-master\twitch.py", line 981, in get_auth
    await self._auth_state.validate()
  File "E:\TwitchDropsMiner-master\twitch.py", line 198, in validate
    await self._validate()
  File "E:\TwitchDropsMiner-master\twitch.py", line 226, in _validate
    self.access_token = await self._login()
  File "E:\TwitchDropsMiner-master\twitch.py", line 170, in _login
    raise LoginException(login_response["error"])
exceptions.LoginException: Oops! We encountered an unexpected error. Please try again.

Exiting...

Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment]
Hello o/

Please see #40.

**Comment by LaoMingZi** [comment]
sorry,I still haven't solved this problem. 
Delete COOKIE.

**Comment by LaoMingZi** [comment]
I don't understand.

**Comment by DevilXD** [comment]
This application doseen't work anymore, and I cannot fix it because of the anti-bot measures Twitch has implemented. Everything is explained in issue #40 <- please click on it to see the discussion on the topic.

**Comment by LaoMingZi** [comment]
Just checking the upcoming Twitch Drops will also help you a lot.
