### ISSUE TITLE
GQL Exception "service error"

### ISSUE THREAD

**Issue by BLACK4585** [DevilXD/TwitchDropsMiner#615]
Hey,
I get this error every time I start the miner.
```
20:14:34: Fatal error encountered:
20:14:34: 
20:14:34: Traceback (most recent call last):
20:14:34:   File "main.py", line 155, in main
20:14:34:   File "twitch.py", line 587, in run
20:14:34:   File "twitch.py", line 747, in _run
20:14:34:   File "twitch.py", line 1657, in bulk_check_online
20:14:34:   File "asyncio\tasks.py", line 571, in _wait_for_one
20:14:34:   File "twitch.py", line 1387, in gql_request
20:14:34: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
```

**Comment by JourneyOver** [comment]
Duplicate of #590

**Comment by BLACK4585** [comment]
whoopsie sry
