### ISSUE TITLE
Exception in _watch_loop task

### ISSUE THREAD

**Issue by zsnzzg** [DevilXD/TwitchDropsMiner#631]
```py
02:49:33: 正在观看: mL7support
02:49:34: ERROR: Exception in _watch_loop task
02:49:34: Traceback (most recent call last):
02:49:34:   File "O:\zsn\TDM\TwitchDropsMiner\utils.py", line 132, in wrapper
02:49:34:     await afunc(*args, **kwargs)
02:49:34:   File "O:\zsn\TDM\TwitchDropsMiner\twitch.py", line 888, in _watch_loop
02:49:34:     succeeded: bool = await channel.send_watch()
02:49:34:   File "O:\zsn\TDM\TwitchDropsMiner\channel.py", line 377, in send_watch
02:49:34:     async with self._twitch.request(
02:49:34:   File "C:\Users\snow\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
02:49:34:     return await anext(self.gen)
02:49:34:   File "O:\zsn\TDM\TwitchDropsMiner\twitch.py", line 1313, in request
02:49:34:     response = await self.gui.coro_unless_closed(
02:49:34:   File "O:\zsn\TDM\TwitchDropsMiner\gui.py", line 2203, in coro_unless_closed
02:49:34:     return await next(iter(done))
02:49:34:   File "O:\zsn\TDM\TwitchDropsMiner\env\lib\site-packages\aiohttp\client.py", line 1328, in send
02:49:34:     return self._coro.send(arg)
02:49:34:   File "O:\zsn\TDM\TwitchDropsMiner\env\lib\site-packages\aiohttp\client.py", line 576, in _request
02:49:34:     raise err_exc_cls(url)
02:49:34: aiohttp.client_exceptions.InvalidUrlClientError: %3C/BODY%3E%3C/HTML%3E
02:49:34: 正在退出...
02:49:36: 
02:49:36: 应用程序已终止，请关闭窗口以退出应用程序.
```

**Comment by DevilXD** [comment]
Hello,

Thank you for the report. The error suggests one of two things, either some kind of global redirect system has loaded up an HTML page in places of stream data, or it's some kind of an error from Twitch that returned HTML instead of text. Both are likely, but the first one is more likely than the second.

The redirect system usually exists where you have to login into the network to use it. The miner has a way of detecting that, but only during the first setup run. If the network requires you to relogin after some time, this error could be the result of it.

Without access to such a network, it's not really possible for me to determine the best course of action here. I'll try implementing the "unexpected content" in the watch loop handler, but it's going to be a "blind fix" sort of thing, without me being able to test it properly.

**Comment by javilak** [comment]
Delete cookies.jar and login again can solive this

**Comment by Secas69** [comment]
I have the same problem after updating too the latest version 

> The miner has a way of detecting that, but only during the first setup run.

I have reinstalled the miner and there was nothing that got detected @DevilXD 

>Delete cookies.jar and login again can solive this

 i have tried this and it didnt work @javilak did you change something else?

Befor reinstall  the Error cam after some time when the miner wanted too switch between channels
After reinstall the error comes after starting the miner

**Comment by Secas69** [comment]
![Image](https://github.com/user-attachments/assets/ff0f4257-ade4-461c-8524-f9550504f17a)

![Image](https://github.com/user-attachments/assets/7b000e66-7a23-4ce9-9647-93217a86f99f)

![Image](https://github.com/user-attachments/assets/09165717-15a8-4544-abda-9ea41c711a57)

**Comment by Secas69** [comment]
this always happens when a channel goes offline and the miner wanna switch 
when this happens i need too restart the machine or it will happen again when i restart the program 
i deleted everything and reinstalled and it happend again
Im using the latest version

**Comment by DevilXD** [comment]
Hello,

I am unable to reproduce the issue. The traceback points at the miner receiving a response that isn't what it expected to receive, which breaks everything.

- Are you using an internet connection that may automatically serve you a special website for login purposes?
- Are you using a proxy?
- Are you running multiple copies of the miner at the same time?
- Are you watching any streams in the browser during mining process?
- Does the Twitch website load and behave normally, right after the miner reports an error?

**Comment by gbzret4d** [comment]
I habe the same problem so ill answer

> Hello,
> 
> I am unable to reproduce the issue. The traceback points at the miner receiving a response that isn't what it expected to receive, which breaks everything.
> 
>     * Are you using an internet connection that may automatically serve you a special website for login purposes?
no
>     * Are you using a proxy?
no
>     * Are you running multiple copies of the miner at the same time?
no
>     * Are you watching any streams in the browser during mining process?
no
>     * Does the Twitch website load and behave normally, right after the miner reports an error?
yes

**Comment by DevilXD** [comment]
Thank you. I'm still unable to reproduce the issue. Without a way to reproduce this, I cannot fix it.

**Comment by gbzret4d** [comment]
I tried to delete the cookies and logged in again but problem still occurs. New log:

```
02:00:26: ERROR: Stream state change for a non-existing channel: 183287722
03:30:05: ERROR: Exception in _watch_loop task
03:30:05: Traceback (most recent call last):
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
03:30:05:     sock.connect(address)
03:30:05: BlockingIOError: [Errno 115] Die Operation ist jetzt in Bearbeitung
03:30:05: 
03:30:05: During handling of the above exception, another exception occurred:
03:30:05: 
03:30:05: Traceback (most recent call last):
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/src/utils.py", line 132, in wrapper
03:30:05:     await afunc(*args, **kwargs)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 902, in _watch_loop
03:30:05:     context = await self.gql_request(
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 1357, in gql_request
03:30:05:     async with self.request(
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
03:30:05:     return await anext(self.gen)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 1312, in request
03:30:05:     response = await self.gui.coro_unless_closed(
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/src/gui.py", line 2205, in coro_unless_closed
03:30:05:     return await next(iter(done))
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/client.py", line 1409, in send
03:30:05:     return self._coro.send(arg)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/client.py", line 703, in _request
03:30:05:     conn = await self._connector.connect(
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 548, in connect
03:30:05:     proto = await self._create_connection(req, traces, timeout)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1056, in _create_connection
03:30:05:     _, proto = await self._create_direct_connection(req, traces, timeout)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1383, in _create_direct_connection
03:30:05:     transp, proto = await self._wrap_create_connection(
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1116, in _wrap_create_connection
03:30:05:     sock = await aiohappyeyeballs.start_connection(
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 127, in start_connection
03:30:05:     raise first_exception
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohappyeyeballs/_staggered.py", line 132, in run_one_coro
03:30:05:     result = await coro_fn()
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 208, in _connect_sock
03:30:05:     await loop.sock_connect(sock, address)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 499, in sock_connect
03:30:05:     self._sock_connect(fut, sock, address)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 515, in _sock_connect
03:30:05:     self._ensure_fd_no_transport(fd)
03:30:05:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 248, in _ensure_fd_no_transport
03:30:05:     raise RuntimeError(
03:30:05: RuntimeError: File descriptor 30 is used by transport <_SelectorSocketTransport fd=30 read=polling write=<idle, bufsize=0>>
03:30:06: Fatal error encountered:
03:30:06: 
03:30:06: Traceback (most recent call last):
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
03:30:06:     sock.connect(address)
03:30:06: BlockingIOError: [Errno 115] Die Operation ist jetzt in Bearbeitung
03:30:06: 
03:30:06: During handling of the above exception, another exception occurred:
03:30:06: 
03:30:06: Traceback (most recent call last):
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/main.py", line 155, in main
03:30:06:     await client.run()
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 588, in run
03:30:06:     await self._run()
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 638, in _run
03:30:06:     await self.fetch_inventory()
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 1484, in fetch_inventory
03:30:06:     chunk_campaigns_data = await coro
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
03:30:06:     return f.result()  # May raise f.exception().
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 1441, in fetch_campaigns
03:30:06:     response_list: list[JsonType] = await self.gql_request(
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 1357, in gql_request
03:30:06:     async with self.request(
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
03:30:06:     return await anext(self.gen)
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/twitch.py", line 1312, in request
03:30:06:     response = await self.gui.coro_unless_closed(
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/src/gui.py", line 2205, in coro_unless_closed
03:30:06:     return await next(iter(done))
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/client.py", line 1409, in send
03:30:06:     return self._coro.send(arg)
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/client.py", line 703, in _request
03:30:06:     conn = await self._connector.connect(
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 548, in connect
03:30:06:     proto = await self._create_connection(req, traces, timeout)
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1056, in _create_connection
03:30:06:     _, proto = await self._create_direct_connection(req, traces, timeout)
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1383, in _create_direct_connection
03:30:06:     transp, proto = await self._wrap_create_connection(
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1116, in _wrap_create_connection
03:30:06:     sock = await aiohappyeyeballs.start_connection(
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 127, in start_connection
03:30:06:     raise first_exception
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohappyeyeballs/_staggered.py", line 132, in run_one_coro
03:30:06:     result = await coro_fn()
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 208, in _connect_sock
03:30:06:     await loop.sock_connect(sock, address)
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 499, in sock_connect
03:30:06:     self._sock_connect(fut, sock, address)
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 515, in _sock_connect
03:30:06:     self._ensure_fd_no_transport(fd)
03:30:06:   File "/tmp/.mount_TwitchaxQf2m/usr/lib/python3.10/asyncio/selector_events.py", line 248, in _ensure_fd_no_transport
03:30:06:     raise RuntimeError(
03:30:06: RuntimeError: File descriptor 30 is used by transport <_SelectorSocketTransport fd=30 read=polling write=<idle, bufsize=0>>
03:30:06: 
03:30:06: Exiting...
03:30:07: 
03:30:07: Application Terminated.
03:30:07: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
I don't even know how on earth have you managed to get a traceback like that, but it implies something is wrong either with your operating system, or your internet connection, or both. Neither of those two I am able to fix in any way.

Have you tried running the PyInstaller version instead of the AppImage one? Have you tried running the miner from source code?

**Comment by gbzret4d** [comment]
> I don't even know how on earth have you managed to get a traceback like that, but it implies something is wrong either with your operating system, or your internet connection, or both. Neither of those two I am able to fix in any way.
> 
> Have you tried running the PyInstaller version instead of the AppImage one? Have you tried running the miner from source code?

With the latest appimage its working so far. If it happens again ill try it with the pyinstaller. It runs at a server with a static internet connection so this should not be the issue.

**Comment by DevilXD** [comment]
Since no more reports were made for this issue, I'm assuming this has been resolved by now.
