### ISSUE TITLE
Issue when running the EXE file.

### ISSUE THREAD

**Issue by Ramitzu** [DevilXD/TwitchDropsMiner#642]
I am a big noob when it comes to coding and python and everything, and I am sure there are a lot of people who would love to get a solution to this error. Error goes like this: 
Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "truststore_init_.py", line 17, in <module>
  File "ssl.py", line 771, in create_default_context
  File "ssl.py", line 592, in load_default_certs
  File "ssl.py", line 584, in _load_windows_store_certs
ssl.SSLError: not enough data: cadata does not contain a certificate (_ssl.c:4015)

**Comment by DarkRedFish** [comment]
I also have the same issue since a couple of days, everything was working perfectly fine before. In my case the admin workaround is not working. So i guess I will have to take a little more time to see if your python version proposal is working

**Comment by DevilXD** [comment]
I'd need to upgrade the lowest Python version up to 3.12 to fix this bug, per this comment: https://github.com/python/cpython/issues/79846#issuecomment-2278071739 As it doesn't qualify as a security fix, it won't be backported to 3.10 or 3.11, even though they're still consider supported.

I guess I'll keep this open until the upgrade. For now, if anyone finds this later: using Python 3.12 to build the executable (or run the miner from source) should help resolve the issue.
