### ISSUE TITLE
TypeError: Passing coroutines is forbidden, use tasks explicitly

### ISSUE THREAD

**Issue by Emlembow** [DevilXD/TwitchDropsMiner#71]
```
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 177, in <module>
  File "asyncio\base_events.py", line 650, in run_until_complete
  File "twitch.py", line 351, in run
  File "twitch.py", line 371, in _run
  File "twitch.py", line 914, in get_auth
  File "twitch.py", line 136, in validate
  File "twitch.py", line 145, in _validate
  File "contextlib.py", line 204, in __aenter__
  File "twitch.py", line 938, in request
  File "gui.py", line 1926, in coro_unless_closed
  File "asyncio\tasks.py", line 415, in wait
TypeError: Passing coroutines is forbidden, use tasks explicitly.

Exiting...

Application Terminated.
Close the window to exit the application.

```

**Comment by DevilXD** [comment]
Hello o/

Is this from the latest master I've just pushed out?

**Comment by Emlembow** [comment]
This was from one version back. I just rebuilt with the latest commit and now I get this:

```
Fatal error encountered:

Traceback (most recent call last):
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\main.py", line 177, in <module>
    loop.run_until_complete(client.run())
  File "C:\Users\$User\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\twitch.py", line 351, in run
    await self._run()
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\twitch.py", line 371, in _run
    auth_state = await self.get_auth()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\twitch.py", line 914, in get_auth
    await self._auth_state.validate()
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\twitch.py", line 136, in validate
    await self._validate()
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\twitch.py", line 145, in _validate
    async with self._twitch.request("GET", BASE_URL) as response:
  File "C:\Users\$User\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\twitch.py", line 938, in request
    response = await self.gui.coro_unless_closed(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$User\Documents\GitHub\TwitchDropsMiner\gui.py", line 1926, in coro_unless_closed
    done, pending = await asyncio.wait(
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$User\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

Exiting...

Application Terminated.
Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Are you using Python 3.11 by chance?

**Comment by Emlembow** [comment]
I am

**Comment by DevilXD** [comment]
Please try the latest master branch, now that I've added handling for this: https://github.com/DevilXD/TwitchDropsMiner/commit/683d2fd755f966a64f796eeaefc5fbe8f7b63413

**Comment by Emlembow** [comment]
```
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 177, in <module>
  File "asyncio\base_events.py", line 650, in run_until_complete
  File "twitch.py", line 351, in run
  File "twitch.py", line 371, in _run
  File "twitch.py", line 914, in get_auth
  File "twitch.py", line 136, in validate
  File "twitch.py", line 145, in _validate
  File "contextlib.py", line 204, in __aenter__
  File "twitch.py", line 938, in request
  File "gui.py", line 1929, in coro_unless_closed
  File "asyncio\tasks.py", line 415, in wait
TypeError: Passing coroutines is forbidden, use tasks explicitly.

Exiting...

Application Terminated.
Close the window to exit the application.
```

**Comment by DevilXD** [comment]
And after https://github.com/DevilXD/TwitchDropsMiner/commit/2306fc1331dd4559dbc7e5fc6575a11e087ef160?

**Comment by DevilXD** [comment]
Actually, it may still be wrong, so I just pushed out https://github.com/DevilXD/TwitchDropsMiner/commit/024ad975b95e6cde269fca247f0c86f2c6b6b43c Please let me know if that fixes this issue on 3.11.

**Comment by Emlembow** [comment]
✅ Confirmed. The coroutines issue has been resolved. Working with [024ad97](https://github.com/DevilXD/TwitchDropsMiner/commit/024ad975b95e6cde269fca247f0c86f2c6b6b43c) on Python 3.11.0

**Comment by Emlembow** [comment]
Closed
