### ISSUE TITLE
help!when i login can not start

### ISSUE THREAD

**Issue by domious4888** [DevilXD/TwitchDropsMiner#81]
i get this 
plz help me

Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 423, in run
  File "twitch.py", line 443, in _run
  File "twitch.py", line 986, in get_auth
  File "twitch.py", line 208, in validate
  File "twitch.py", line 233, in _validate
  File "twitch.py", line 125, in _login
  File "aiohttp\client_reqrep.py", line 1119, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 128 (char 127)

Exiting...

Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment]
Hello o/

Please see #68. This is already fixed on the latest master branch, and `v15` is on it's way to a release. You can run it from source for now if you know how, but otherwise, you'll just need to wait.

**Comment by domious4888** [comment]
> Hello o/
> 
> Please see #68. This is already fixed on the latest master branch, and `v15` is on it's way to a release. You can run it from source for now if you know how, but otherwise, you'll just need to wait.

Thanks!
