### ISSUE TITLE
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 4603904 out of 6904173 bytes>

### ISSUE THREAD

**Issue by hadenting** [DevilXD/TwitchDropsMiner#88]
```
请先登录以访问更多内容.
Opening Chrome...
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 179, in <module>
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "twitch.py", line 351, in run
  File "twitch.py", line 370, in _run
  File "twitch.py", line 913, in get_auth
  File "twitch.py", line 136, in validate
  File "twitch.py", line 161, in _validate
  File "twitch.py", line 107, in _login
  File "gui.py", line 506, in ask_login
  File "gui.py", line 1970, in coro_unless_closed
  File "concurrent\futures\thread.py", line 58, in run
  File "gui.py", line 497, in <lambda>
  File "seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
  File "undetected_chromedriver\__init__.py", line 240, in __init__
  File "undetected_chromedriver\patcher.py", line 130, in auto
  File "undetected_chromedriver\patcher.py", line 166, in fetch_package
  File "urllib\request.py", line 280, in urlretrieve
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 4603904 out of 6904173 bytes>

正在退出...

应用程序已终止，请关闭窗口以退出应用程序。


```
Maybe there is something wrong with my installation environment?

**Comment by DevilXD** [comment]
Looks like a general issue with your internet connection.
