### ISSUE TITLE
Fatal Error encountered when choosing Lost Ark from list of games

### ISSUE THREAD

**Issue by Abisteen** [DevilXD/TwitchDropsMiner#9]
Other games work, but when I click Lost Ark in Game Selector, the following occurs:

Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 101, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 234, in run
  File "websocket.py", line 338, in remove_topics
  File "websocket.py", line 267, in remove_topics
  File "websocket.py", line 66, in set_status
  File "gui.py", line 165, in update
TypeError: You need to provide at least one of: status, topics

Exiting...

Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment]
This is now fixed in `v10`: https://github.com/DevilXD/TwitchDropsMiner/releases
