### ISSUE TITLE
Fatal error when trying to sign in

### ISSUE THREAD

**Issue by fhuihnlsmnzdlkfsdjnlkfjsdn** [DevilXD/TwitchDropsMiner#94]
Disregard. New to github and didnt see the #68

**Comment by DevilXD** [comment]
This is already fixed in `v15`, but you'd need to either build your own executable, or wait for an official release. Just so you know, I tried to make building your own executable a semi-easy process, even for people who know nothing about programming - all you have to be able to, is follow instructions. Please let me know if you'd be interested.

**Comment by Sakura2466** [comment]
> 这已在 中修复`v15`，但您需要构建自己的可执行文件，或等待正式发布。就像你知道的那样，我试图让构建你自己的可执行文件成为一个半简单的过程，即使对于那些对编程一无所知的人来说也是如此 - 你所要做的就是按照说明进行操作。如果您有兴趣，请告诉我。
I'm interested

**Comment by Sakura2466** [comment]
@DevilXD i can help to test

**Comment by cikichen** [comment]
Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 423, in run
  File "twitch.py", line 443, in _run
  File "twitch.py", line 986, in get_auth
  File "twitch.py", line 208, in validate
  File "twitch.py", line 233, in _validate
  File "twitch.py", line 125, in _login
  File "aiohttp\client_reqrep.py", line 1119, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 128 (char 127)

**Comment by DevilXD** [comment]
@cikichen There's an issue open for that already, please check the pinned issues next time: #68

@Sakura2466 I've created a guide on how to run this project from source and build an executable yourself here: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running
